import { Ionicons } from '@expo/vector-icons';
import { useEffect,useMemo,useState } from 'react';
import { Alert,FlatList,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { loadSEOIssues,loadSEOKeywords,loadSEOProfiles,saveSEOIssues } from '../src/storage/seoStorage';
import { colors } from '../src/theme';
import { SEOIssue,SEOIssueStatus,SEOKeyword,SEOProfile } from '../src/types/seo';

type Tab='overview'|'issues'|'keywords'|'local';
const statuses:SEOIssueStatus[]=['open','in_progress','fixed','ignored'];

export default function SEO(){
 const [tab,setTab]=useState<Tab>('overview'),[profiles,setProfiles]=useState<SEOProfile[]>([]),[issues,setIssues]=useState<SEOIssue[]>([]),[keywords,setKeywords]=useState<SEOKeyword[]>([]);
 useEffect(()=>{Promise.all([loadSEOProfiles(),loadSEOIssues(),loadSEOKeywords()]).then(([p,i,k])=>{setProfiles(p);setIssues(i);setKeywords(k)}).catch(()=>Alert.alert('SEO data load failed'));},[]);
 const p=profiles[0],open=useMemo(()=>issues.filter(x=>x.status!=='fixed').length,[issues]);
 async function patch(x:SEOIssue,status:SEOIssueStatus){const n=issues.map(i=>i.id===x.id?{...i,status}:i);setIssues(n);try{await saveSEOIssues(n)}catch{Alert.alert('Save failed')}}
 return <SafeAreaView style={s.page} edges={['top']}><View style={s.header}><Text style={s.head}>SEO + Local SEO</Text><Text style={s.sub}>Audit, issues, keywords and local visibility</Text></View>
 <View style={s.notice}><Ionicons name="information-circle-outline" size={20} color={colors.green}/><Text style={s.noticeText}>Demo audit · Search Console and Google Business data are not connected yet.</Text></View>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{(['overview','issues','keywords','local'] as Tab[]).map(x=><Chip key={x} text={x} on={tab===x} press={()=>setTab(x)}/>)}</ScrollView>
 {tab==='overview'&&<ScrollView contentContainerStyle={s.body}>{p?<><View style={s.hero}><Text style={s.client}>{p.clientName}</Text><Text style={s.site}>{p.website}</Text><Text style={s.score}>{p.overall}</Text><Text style={s.scoreLabel}>Demo SEO score / 100</Text></View><View style={s.grid}><Score name="On-page" value={p.onPage}/><Score name="Technical" value={p.technical}/><Score name="Content" value={p.content}/><Score name="Local SEO" value={p.local}/></View><View style={s.summary}><Text style={s.section}>Audit summary</Text><Text style={s.line}>Open issues: {open}</Text><Text style={s.line}>Tracked keywords: {keywords.length}</Text><Text style={s.line}>Last audit: {p.lastAudit}</Text></View></>:<Text style={s.empty}>No SEO profile.</Text>}</ScrollView>}
 {tab==='issues'&&<FlatList data={issues} keyExtractor={x=>x.id} contentContainerStyle={s.body} renderItem={({item})=><Issue item={item} patch={patch}/>} ListEmptyComponent={<Text style={s.empty}>No SEO issues.</Text>}/>}
 {tab==='keywords'&&<FlatList data={keywords} keyExtractor={x=>x.id} contentContainerStyle={s.body} renderItem={({item})=><Keyword item={item}/>} ListEmptyComponent={<Text style={s.empty}>No keywords.</Text>}/>}
 {tab==='local'&&<ScrollView contentContainerStyle={s.body}><View style={s.card}><Text style={s.section}>Google Business Profile</Text><Info label="Connection" value={p?.googleBusiness||'Not connected'}/><Info label="Local target" value="Karur, Tamil Nadu"/><Info label="Reviews" value="API not connected"/><Info label="Google Posts" value="Planning only"/></View><View style={s.card}><Text style={s.section}>Local SEO checklist</Text>{['Business name, address and phone consistency','Service and location relevance','Google Business categories and services','Review workflow','Local landing pages','Local citations'].map(x=><View key={x} style={s.check}><Ionicons name="ellipse-outline" size={18} color={colors.green}/><Text style={s.checkText}>{x}</Text></View>)}</View></ScrollView>}
 </SafeAreaView>;
}
function Issue({item,patch}:{item:SEOIssue;patch:(x:SEOIssue,s:SEOIssueStatus)=>void}){return <View style={s.card}><View style={s.issueTop}><View style={s.severity}><Text style={s.severityText}>{item.severity}</Text></View><Text style={s.category}>{item.category}</Text></View><Text style={s.issueTitle}>{item.title}</Text><Text style={s.url}>{item.url}</Text><Text style={s.label}>WHY IT MATTERS</Text><Text style={s.copy}>{item.why}</Text><Text style={s.label}>RECOMMENDED FIX</Text><Text style={s.copy}>{item.recommendation}</Text><View style={s.statuses}>{statuses.map(x=><Chip key={x} text={x.replace('_',' ')} on={item.status===x} press={()=>patch(item,x)}/>)}</View></View>}
function Keyword({item}:{item:SEOKeyword}){return <View style={s.card}><Text style={s.issueTitle}>{item.keyword}</Text><Text style={s.url}>{item.location} · {item.intent}</Text><View style={s.kwrow}><Info label="Current" value={item.currentPosition}/><Info label="Target" value={item.targetPosition}/></View></View>}
function Score({name,value}:{name:string;value:number}){return <View style={s.scoreCard}><Text style={s.smallScore}>{value}</Text><Text style={s.scoreName}>{name}</Text></View>}
function Info({label,value}:{label:string;value:string}){return <View style={s.info}><Text style={s.infoLabel}>{label}</Text><Text style={s.infoValue}>{value}</Text></View>}
function Chip({text,on,press}:{text:string;on:boolean;press:()=>void}){return <Pressable style={[s.chip,on&&s.chipOn]} onPress={press}><Text style={[s.chipText,on&&s.chipTextOn]}>{text}</Text></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.cream},header:{padding:20,paddingBottom:10},head:{fontSize:29,fontWeight:'900',color:colors.green},sub:{color:colors.muted,marginTop:4},notice:{marginHorizontal:20,marginBottom:12,padding:12,borderRadius:14,backgroundColor:'#E9F1EE',flexDirection:'row',gap:8,alignItems:'center'},noticeText:{flex:1,color:colors.green,fontWeight:'700',fontSize:12},tabs:{paddingHorizontal:20,gap:8,paddingBottom:12},chip:{height:38,paddingHorizontal:14,borderRadius:19,borderWidth:1,borderColor:'#D8D2BA',justifyContent:'center'},chipOn:{backgroundColor:colors.green,borderColor:colors.green},chipText:{color:colors.green,fontWeight:'800',textTransform:'capitalize'},chipTextOn:{color:'white'},body:{padding:20,paddingTop:8,paddingBottom:80},hero:{backgroundColor:colors.green,borderRadius:22,padding:22},client:{color:'white',fontSize:22,fontWeight:'900'},site:{color:'#DCEAE4',marginTop:4},score:{color:'white',fontSize:58,fontWeight:'900',marginTop:18},scoreLabel:{color:'#DCEAE4',fontWeight:'700'},grid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:12},scoreCard:{width:'48%',backgroundColor:'white',borderRadius:17,padding:16},smallScore:{fontSize:28,fontWeight:'900',color:colors.green},scoreName:{color:colors.muted,fontWeight:'700',marginTop:3},summary:{backgroundColor:'white',borderRadius:18,padding:17,marginTop:12},section:{fontSize:18,fontWeight:'900',color:colors.text,marginBottom:10},line:{color:colors.text,marginTop:7,fontWeight:'600'},card:{backgroundColor:'white',borderRadius:18,padding:16,marginBottom:12},issueTop:{flexDirection:'row',alignItems:'center',gap:8},severity:{backgroundColor:'#FFF1C9',borderRadius:8,paddingHorizontal:8,paddingVertical:4},severityText:{color:'#805B00',fontWeight:'900',textTransform:'uppercase',fontSize:10},category:{color:colors.green2,fontWeight:'800'},issueTitle:{fontSize:18,fontWeight:'900',color:colors.text,marginTop:10},url:{color:colors.muted,marginTop:4,marginBottom:12},label:{fontSize:10,fontWeight:'900',color:colors.muted,marginTop:10},copy:{color:colors.text,lineHeight:20,marginTop:4},statuses:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:15},kwrow:{flexDirection:'row',gap:8},info:{flex:1,backgroundColor:'#F8F5E9',borderRadius:12,padding:11,marginTop:6},infoLabel:{fontSize:10,color:colors.muted,textTransform:'uppercase'},infoValue:{fontWeight:'800',color:colors.text,marginTop:3},check:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:9},checkText:{color:colors.text,fontWeight:'600'},empty:{textAlign:'center',color:colors.muted,marginTop:70}});
